# # # # # # # # # # # # # # # #
#                             #
#          НАСТРОЙКИ          #
#                             #
# # # # # # # # # # # # # # # #


#  Срок оффлайна в месяцах
period_old: 12
# Очистка при смерти игрока
dead_player: false
# Очистка при перезагрузке
reboot: false

# Список плагинов для очистки
autorank: true
luckperms: true
litebans: true
mcmmo: false

# LITE BANS SETTINGS(hours):
min_time: 1
max_time: 168

# Белый список игроков (исключения)
whitelist:
  - SovietUnion